revert(darwin): switch to brew casks for most custom apps
This reverts commit d6545e6e2f6529bde2074705839bc4bec1325ee2.

Currently does not work as intended:
Error: Invalid usage: Options --cask and --ignore-dependencies are mutually exclusive.